function plotWaypoints(waypointsInOrder, states)
% Plot waypoints.
%
% Inputs:
%  - waypointsInOrder
%  - states        A 1-by-N vector with 0 for not visited, 1 for visited
%                  and incorrect, and 2 for visited and correct.

persistent wp_no1;
persistent wp_no2;
persistent wp_vc1;
persistent wp_vc2;
persistent wp_vi1;
persistent wp_vi2;
persistent wp_texts;

delete(wp_no1);
delete(wp_no2);
delete(wp_vc1);
delete(wp_vc2);
delete(wp_vi1);
delete(wp_vi2);
delete(wp_texts);

activateCurrentPlot();

legend1 = "Waypoints";
legend2 = "Incorrect Waypoints";
legend3 = "Correct Waypoints";
markerSize = 7;
lineWidth = 2;

waypoints0 = waypointsInOrder(states == 0, :);
waypoints1 = waypointsInOrder(states == 1, :);
waypoints2 = waypointsInOrder(states == 2, :);

if size(waypoints0, 1) >= 1
    wp_no1 = plot( ...
        waypoints0(1, 1), ...
        waypoints0(1, 2), ...
        "*", Color = "blue", ...
        MarkerSize = markerSize, LineWidth = lineWidth, ...
        DisplayName = legend1);
end
if size(waypoints0, 1) >= 2
    wp_no2 = plot( ...
        waypoints0(2:end, 1), ...
        waypoints0(2:end, 2), ...
        "*", Color = "blue", ...
        MarkerSize = markerSize, LineWidth = lineWidth, ...
        DisplayName = legend1, HandleVisibility = "off");
end

if size(waypoints1, 1) >= 1
    wp_vi1 = plot( ...
        waypoints1(1, 1), ...
        waypoints1(1, 2), ...
        "*", Color = "red", ...
        MarkerSize = markerSize, LineWidth = lineWidth, ...
        DisplayName = legend2);
end
if size(waypoints1, 1) >= 2
    wp_vi2 = plot( ...
        waypoints1(2:end, 1), ...
        waypoints1(2:end, 2), ...
        "*", Color = "red", ...
        MarkerSize = markerSize, LineWidth = lineWidth, ...
        DisplayName = legend2, HandleVisibility = "off");
end

if size(waypoints2, 1) >= 1
    wp_vc1 = plot( ...
        waypoints2(1, 1), ...
        waypoints2(1, 2), ...
        "*", Color = "green", ...
        MarkerSize = markerSize, LineWidth = lineWidth, ...
        DisplayName = legend3);
end
if size(waypoints2, 1) >= 2
    wp_vc2 = plot( ...
        waypoints2(2:end, 1), ...
        waypoints2(2:end, 2), ...
        "*", Color = "green", ...
        MarkerSize = markerSize, LineWidth = lineWidth, ...
        DisplayName = legend3, HandleVisibility = "off");
end

wp_texts = [];
for i=1:size(waypointsInOrder, 1)
    wp_texts = [wp_texts ...
        text(waypointsInOrder(i, 1) + 0.1, ...
            waypointsInOrder(i, 2), ...
            num2str(i))];
end

end
