function plotParticles(particles)
% Plot particles in initial localization.

persistent pointsPlot1;
persistent linesPlot;
persistent pointsPlot;

delete(pointsPlot1);
delete(linesPlot);
delete(pointsPlot);

lineStartDist = 0;
lineEndDist = .2;
lineColor = "#2196F3";
pointColor = [0.1294, 0.5882, 0.9529];

filter = particles.x(end, :) > -998;
px = particles.x(end, filter);
py = particles.y(end, filter);
pt = particles.theta(end, filter);

x1 = px(end, 2:end) + ...
    lineStartDist * cos(pt(end, 2:end));
y1 = py(end, 2:end) + ...
    lineStartDist * sin(pt(end, 2:end));
x2 = px(end, 2:end) + ...
    lineEndDist * cos(pt(end, 2:end));
y2 = py(end, 2:end) + ...
    lineEndDist * sin(pt(end, 2:end));

activateCurrentPlot();

linesPlot = plot( ...
    [x1; x2], ...
    [y1; y2], ...
    '-', ...
    LineWidth = 3, Color = lineColor, HandleVisibility = "off");
pointsPlot1 = scatter( ...
    px(end, 2:3), ...
    py(end, 2:3), ...
    100, ...
    pointColor, ...
    LineWidth = 2, DisplayName = "Particle");
pointsPlot = scatter( ...
    px(end, 4:end), ...
    py(end, 4:end), ...
    100, ...
    pointColor, ...
    LineWidth = 2, HandleVisibility = "off");

end
